package com.camjewell.betterruneloadouts;

import java.util.List;
import java.util.stream.Collectors;
import net.runelite.api.gameval.SpriteID;

/**
 * A selectable theme icon for a loadout's Load button, plus the curated
 * catalog offered by {@link RunePouchLoadoutIconPicker}.
 */
class RunePouchLoadoutIcon
{
	// Purely a sentinel value compared against to decide whether a slot is
	// "unset" (RunePouchGridManager.applyIconSlot renders the actual unset
	// placeholder as an item icon, not this sprite) — the only place this
	// sprite is ever actually drawn is the picker's own "Default" grid
	// entry, so it just needs to visually read as an X there. Confirmed via
	// screenshot that FavouriteIcons.REMOVE (previously used here) renders
	// as a heart, not an X — SpriteID.CROSS is the correct plain X mark.
	static final int DEFAULT_SPRITE_ID = SpriteID.CROSS;
	static final int NO_SECOND_ICON = -1;

	final int spriteId;
	final String name;

	RunePouchLoadoutIcon(int spriteId, String name)
	{
		this.spriteId = spriteId;
		this.name = name;
	}

	static List<RunePouchLoadoutIcon> search(String query)
	{
		if (query.isEmpty())
		{
			return ICONS;
		}

		String lower = query.toLowerCase();
		return ICONS.stream()
			.filter(icon -> icon.name.toLowerCase().contains(lower))
			.collect(Collectors.toList());
	}

	static final List<RunePouchLoadoutIcon> ICONS = List.of(
		new RunePouchLoadoutIcon(DEFAULT_SPRITE_ID, "Default"),

		new RunePouchLoadoutIcon(SpriteID.Magicon.WIND_STRIKE, "Wind Strike"),
		new RunePouchLoadoutIcon(SpriteID.Magicon.WATER_STRIKE, "Water Strike"),
		new RunePouchLoadoutIcon(SpriteID.Magicon.EARTH_STRIKE, "Earth Strike"),
		new RunePouchLoadoutIcon(SpriteID.Magicon.FIRE_STRIKE, "Fire Strike"),
		new RunePouchLoadoutIcon(SpriteID.Magicon.WIND_BOLT, "Wind Bolt"),
		new RunePouchLoadoutIcon(SpriteID.Magicon.WATER_BOLT, "Water Bolt"),
		new RunePouchLoadoutIcon(SpriteID.Magicon.EARTH_BOLT, "Earth Bolt"),
		new RunePouchLoadoutIcon(SpriteID.Magicon.FIRE_BOLT, "Fire Bolt"),
		new RunePouchLoadoutIcon(SpriteID.Magicon.WIND_BLAST, "Wind Blast"),
		new RunePouchLoadoutIcon(SpriteID.Magicon.WATER_BLAST, "Water Blast"),
		new RunePouchLoadoutIcon(SpriteID.Magicon.EARTH_BLAST, "Earth Blast"),
		new RunePouchLoadoutIcon(SpriteID.Magicon.FIRE_BLAST, "Fire Blast"),
		new RunePouchLoadoutIcon(SpriteID.Magicon.WIND_WAVE, "Wind Wave"),
		new RunePouchLoadoutIcon(SpriteID.Magicon.WATER_WAVE, "Water Wave"),
		new RunePouchLoadoutIcon(SpriteID.Magicon.EARTH_WAVE, "Earth Wave"),
		new RunePouchLoadoutIcon(SpriteID.Magicon.FIRE_WAVE, "Fire Wave"),
		new RunePouchLoadoutIcon(SpriteID.Magicon2.WIND_SURGE, "Wind Surge"),
		new RunePouchLoadoutIcon(SpriteID.Magicon2.WATER_SURGE, "Water Surge"),
		new RunePouchLoadoutIcon(SpriteID.Magicon2.EARTH_SURGE, "Earth Surge"),
		new RunePouchLoadoutIcon(SpriteID.Magicon2.FIRE_SURGE, "Fire Surge"),
		new RunePouchLoadoutIcon(SpriteID.Magicon.IBAN_BLAST, "Iban Blast"),
		new RunePouchLoadoutIcon(SpriteID.Magicon2.CHARGE, "Charge"),
		new RunePouchLoadoutIcon(SpriteID.Magicon.FLAMES_OF_ZAMORAK, "Flames of Zamorak"),
		new RunePouchLoadoutIcon(SpriteID.Magicon.CLAWS_OF_GUTHIX, "Claws of Guthix"),
		new RunePouchLoadoutIcon(SpriteID.Magicon.SARADOMIN_STRIKE, "Saradomin Strike"),
		new RunePouchLoadoutIcon(SpriteID.Magicon.CRUMBLE_UNDEAD, "Crumble Undead"),
		new RunePouchLoadoutIcon(SpriteID.Magicon2.BIND, "Bind"),
		new RunePouchLoadoutIcon(SpriteID.Magicon2.SNARE, "Snare"),
		new RunePouchLoadoutIcon(SpriteID.Magicon2.ENTANGLE, "Entangle"),
		new RunePouchLoadoutIcon(SpriteID.Magicon.LUMBRIDGE_TELEPORT, "Lumbridge Teleport"),
		new RunePouchLoadoutIcon(SpriteID.Magicon.FALADOR_TELEPORT, "Falador Teleport"),
		new RunePouchLoadoutIcon(SpriteID.Magicon.VARROCK_TELEPORT, "Varrock Teleport"),
		new RunePouchLoadoutIcon(SpriteID.Magicon.CAMELOT_TELEPORT, "Camelot Teleport"),
		new RunePouchLoadoutIcon(SpriteID.Magicon.ARDOUGNE_TELEPORT, "Ardougne Teleport"),
		new RunePouchLoadoutIcon(SpriteID.Magicon.WATCHTOWER_TELEPORT, "Watchtower Teleport"),
		new RunePouchLoadoutIcon(SpriteID.Magicon2.TROLLHEIM_TELEPORT, "Trollheim Teleport"),
		new RunePouchLoadoutIcon(SpriteID.Magicon2.TELEPORT_TO_HOUSE, "Teleport to House"),
		new RunePouchLoadoutIcon(SpriteID.Magicon2.LUMBRIDGE_HOME_TELEPORT, "Lumbridge Home Teleport"),
		new RunePouchLoadoutIcon(SpriteID.Magicon2.TELEPORT_TO_APE_ATOLL, "Teleport to Ape Atoll"),
		new RunePouchLoadoutIcon(SpriteID.Magicon2.TELEPORT_TO_KOUREND, "Teleport to Kourend"),
		new RunePouchLoadoutIcon(SpriteID.Magicon2.CIVITAS_ILLA_FORTIS_TELEPORT, "Civitas Illa Fortis Teleport"),
		new RunePouchLoadoutIcon(SpriteID.Magicon2.TELE_BLOCK, "Tele Block"),
		new RunePouchLoadoutIcon(SpriteID.Magicon.TELEKINETIC_GRAB, "Telekinetic Grab"),
		new RunePouchLoadoutIcon(SpriteID.Magicon2.TELEOTHER_LUMBRIDGE, "Teleother Lumbridge"),
		new RunePouchLoadoutIcon(SpriteID.Magicon2.TELEOTHER_FALADOR, "Teleother Falador"),
		new RunePouchLoadoutIcon(SpriteID.Magicon2.TELEOTHER_CAMELOT, "Teleother Camelot"),
		new RunePouchLoadoutIcon(SpriteID.Magicon2.TELEPORT_TO_BOUNTY_TARGET, "Teleport to Bounty Target"),
		new RunePouchLoadoutIcon(SpriteID.Magicon.CONFUSE, "Confuse"),
		new RunePouchLoadoutIcon(SpriteID.Magicon.WEAKEN, "Weaken"),
		new RunePouchLoadoutIcon(SpriteID.Magicon.CURSE, "Curse"),
		new RunePouchLoadoutIcon(SpriteID.Magicon.ENFEEBLE, "Enfeeble"),
		new RunePouchLoadoutIcon(SpriteID.Magicon.STUN, "Stun"),
		new RunePouchLoadoutIcon(SpriteID.Magicon.VULNERABILITY, "Vulnerability"),
		new RunePouchLoadoutIcon(SpriteID.Magicon.LOW_LEVEL_ALCHEMY, "Low Level Alchemy"),
		new RunePouchLoadoutIcon(SpriteID.Magicon.HIGH_LEVEL_ALCHEMY, "High Level Alchemy"),
		new RunePouchLoadoutIcon(SpriteID.Magicon.SUPERHEAT_ITEM, "Superheat Item"),
		new RunePouchLoadoutIcon(SpriteID.Magicon.LVL_1_ENCHANT, "Lvl 1 Enchant"),
		new RunePouchLoadoutIcon(SpriteID.Magicon.LVL_2_ENCHANT, "Lvl 2 Enchant"),
		new RunePouchLoadoutIcon(SpriteID.Magicon.LVL_3_ENCHANT, "Lvl 3 Enchant"),
		new RunePouchLoadoutIcon(SpriteID.Magicon.LVL_4_ENCHANT, "Lvl 4 Enchant"),
		new RunePouchLoadoutIcon(SpriteID.Magicon.LVL_5_ENCHANT, "Lvl 5 Enchant"),
		new RunePouchLoadoutIcon(SpriteID.Magicon2.LVL_6_ENCHANT, "Lvl 6 Enchant"),
		new RunePouchLoadoutIcon(SpriteID.Magicon2.LVL_7_ENCHANT, "Lvl 7 Enchant"),
		new RunePouchLoadoutIcon(SpriteID.Magicon2.ENCHANT_CROSSBOW_BOLT, "Enchant Crossbow Bolt"),
		new RunePouchLoadoutIcon(SpriteID.Magicon.CHARGE_WATER_ORB, "Charge Water Orb"),
		new RunePouchLoadoutIcon(SpriteID.Magicon.CHARGE_EARTH_ORB, "Charge Earth Orb"),
		new RunePouchLoadoutIcon(SpriteID.Magicon.CHARGE_FIRE_ORB, "Charge Fire Orb"),
		new RunePouchLoadoutIcon(SpriteID.Magicon.CHARGE_AIR_ORB, "Charge Air Orb"),
		new RunePouchLoadoutIcon(SpriteID.Magicon.BONES_TO_BANANAS, "Bones to Bananas"),
		new RunePouchLoadoutIcon(SpriteID.Magicon2.BONES_TO_PEACHES, "Bones to Peaches"),
		new RunePouchLoadoutIcon(SpriteID.Magicon2.MAGIC_DART, "Magic Dart"),

		new RunePouchLoadoutIcon(SpriteID.Magicon2.ICE_RUSH, "Ice Rush"),
		new RunePouchLoadoutIcon(SpriteID.Magicon2.ICE_BURST, "Ice Burst"),
		new RunePouchLoadoutIcon(SpriteID.Magicon2.ICE_BLITZ, "Ice Blitz"),
		new RunePouchLoadoutIcon(SpriteID.Magicon2.ICE_BARRAGE, "Ice Barrage"),
		new RunePouchLoadoutIcon(SpriteID.Magicon2.SMOKE_RUSH, "Smoke Rush"),
		new RunePouchLoadoutIcon(SpriteID.Magicon2.SMOKE_BURST, "Smoke Burst"),
		new RunePouchLoadoutIcon(SpriteID.Magicon2.SMOKE_BLITZ, "Smoke Blitz"),
		new RunePouchLoadoutIcon(SpriteID.Magicon2.SMOKE_BARRAGE, "Smoke Barrage"),
		new RunePouchLoadoutIcon(SpriteID.Magicon2.BLOOD_RUSH, "Blood Rush"),
		new RunePouchLoadoutIcon(SpriteID.Magicon2.BLOOD_BURST, "Blood Burst"),
		new RunePouchLoadoutIcon(SpriteID.Magicon2.BLOOD_BLITZ, "Blood Blitz"),
		new RunePouchLoadoutIcon(SpriteID.Magicon2.BLOOD_BARRAGE, "Blood Barrage"),
		new RunePouchLoadoutIcon(SpriteID.Magicon2.SHADOW_RUSH, "Shadow Rush"),
		new RunePouchLoadoutIcon(SpriteID.Magicon2.SHADOW_BURST, "Shadow Burst"),
		new RunePouchLoadoutIcon(SpriteID.Magicon2.SHADOW_BLITZ, "Shadow Blitz"),
		new RunePouchLoadoutIcon(SpriteID.Magicon2.SHADOW_BARRAGE, "Shadow Barrage"),
		new RunePouchLoadoutIcon(SpriteID.Magicon2.PADDEWWA_TELEPORT, "Paddewwa Teleport"),
		new RunePouchLoadoutIcon(SpriteID.Magicon2.SENNTISTEN_TELEPORT, "Senntisten Teleport"),
		new RunePouchLoadoutIcon(SpriteID.Magicon2.KHARYRLL_TELEPORT, "Kharyrll Teleport"),
		new RunePouchLoadoutIcon(SpriteID.Magicon2.LASSAR_TELEPORT, "Lassar Teleport"),
		new RunePouchLoadoutIcon(SpriteID.Magicon2.DAREEYAK_TELEPORT, "Dareeyak Teleport"),
		new RunePouchLoadoutIcon(SpriteID.Magicon2.CARRALLANGAR_TELEPORT, "Carrallangar Teleport"),
		new RunePouchLoadoutIcon(SpriteID.Magicon2.ANNAKARL_TELEPORT, "Annakarl Teleport"),
		new RunePouchLoadoutIcon(SpriteID.Magicon2.GHORROCK_TELEPORT, "Ghorrock Teleport"),
		new RunePouchLoadoutIcon(SpriteID.Magicon.CALL_ANIMAL, "Call Animal"),
		new RunePouchLoadoutIcon(SpriteID.Magicon.RAISE_SKELETON, "Raise Skeleton"),
		new RunePouchLoadoutIcon(SpriteID.Magicon.SUMMON_DEMON, "Summon Demon"),

		new RunePouchLoadoutIcon(SpriteID.LunarMagicOn.MAGIC_IMBUE, "Magic Imbue"),
		new RunePouchLoadoutIcon(SpriteID.LunarMagicOn.NPC_CONTACT, "NPC Contact"),
		new RunePouchLoadoutIcon(SpriteID.LunarMagicOn.VENGEANCE, "Vengeance"),
		new RunePouchLoadoutIcon(SpriteID.LunarMagicOn.VENGEANCE_OTHER, "Vengeance Other"),
		new RunePouchLoadoutIcon(SpriteID.LunarMagicOn.CURE_ME, "Cure Me"),
		new RunePouchLoadoutIcon(SpriteID.LunarMagicOn.CURE_GROUP, "Cure Group"),
		new RunePouchLoadoutIcon(SpriteID.LunarMagicOn.CURE_OTHER, "Cure Other"),
		new RunePouchLoadoutIcon(SpriteID.LunarMagicOn.HEAL_GROUP, "Heal Group"),
		new RunePouchLoadoutIcon(SpriteID.LunarMagicOn.HEAL_OTHER, "Heal Other"),
		new RunePouchLoadoutIcon(SpriteID.LunarMagicOn.MOONCLAN_TELEPORT, "Moonclan Teleport"),
		new RunePouchLoadoutIcon(SpriteID.LunarMagicOn.WATERBIRTH_TELEPORT, "Waterbirth Teleport"),
		new RunePouchLoadoutIcon(SpriteID.LunarMagicOn.BARBARIAN_TELEPORT, "Barbarian Teleport"),
		new RunePouchLoadoutIcon(SpriteID.LunarMagicOn.KHAZARD_TELEPORT, "Khazard Teleport"),
		new RunePouchLoadoutIcon(SpriteID.LunarMagicOn.FISHING_GUILD_TELEPORT, "Fishing Guild Teleport"),
		new RunePouchLoadoutIcon(SpriteID.LunarMagicOn.CATHERBY_TELEPORT, "Catherby Teleport"),
		new RunePouchLoadoutIcon(SpriteID.LunarMagicOn.ICE_PLATEAU_TELEPORT, "Ice Plateau Teleport"),
		new RunePouchLoadoutIcon(SpriteID.LunarMagicOn.OURANIA_TELEPORT, "Ourania Teleport"),
		new RunePouchLoadoutIcon(SpriteID.LunarMagicOn.HUMIDIFY, "Humidify"),
		new RunePouchLoadoutIcon(SpriteID.LunarMagicOn.SPELLBOOK_SWAP, "Spellbook Swap"),
		new RunePouchLoadoutIcon(SpriteID.LunarMagicOn.DREAM, "Dream"),

		new RunePouchLoadoutIcon(SpriteID.MagicNecroOn.RESURRECT_LESSER_GHOST, "Resurrect Lesser Ghost"),
		new RunePouchLoadoutIcon(SpriteID.MagicNecroOn._24, "Resurrect Lesser Skeleton"),
		new RunePouchLoadoutIcon(SpriteID.MagicNecroOn._25, "Resurrect Lesser Zombie"),
		new RunePouchLoadoutIcon(SpriteID.MagicNecroOn._44, "Resurrect Superior Ghost"),
		new RunePouchLoadoutIcon(SpriteID.MagicNecroOn.RESURRECT_SUPERIOR_SKELETON, "Resurrect Superior Skeleton"),
		new RunePouchLoadoutIcon(SpriteID.MagicNecroOn._48, "Resurrect Superior Zombie"),
		new RunePouchLoadoutIcon(SpriteID.MagicNecroOn._45, "Resurrect Greater Ghost"),
		new RunePouchLoadoutIcon(SpriteID.MagicNecroOn._47, "Resurrect Greater Skeleton"),
		new RunePouchLoadoutIcon(SpriteID.MagicNecroOn.RESURRECT_GREATER_ZOMBIE, "Resurrect Greater Zombie"),
		new RunePouchLoadoutIcon(SpriteID.MagicNecroOn.ADEPT_REANIMATION, "Adept Reanimation"),
		new RunePouchLoadoutIcon(SpriteID.MagicNecroOn.BASIC_REANIMATION, "Basic Reanimation"),
		new RunePouchLoadoutIcon(SpriteID.MagicNecroOn.EXPERT_REANIMATION, "Expert Reanimation"),
		new RunePouchLoadoutIcon(SpriteID.MagicNecroOn.MASTER_REANIMATION, "Master Reanimation"),
		new RunePouchLoadoutIcon(SpriteID.MagicNecroOn.ARCEUUS_LIBRARY_TELEPORT, "Arceuus Library Teleport"),
		new RunePouchLoadoutIcon(SpriteID.MagicNecroOn.DRAYNOR_MANOR_TELEPORT, "Draynor Manor Teleport"),
		new RunePouchLoadoutIcon(SpriteID.MagicNecroOn.SALVE_GRAVEYARD_TELEPORT, "Salve Graveyard Teleport"),
		new RunePouchLoadoutIcon(SpriteID.MagicNecroOn.MIND_ALTAR_TELEPORT, "Mind Altar Teleport"),
		new RunePouchLoadoutIcon(SpriteID.MagicNecroOn.RESPAWN_TELEPORT, "Respawn Teleport"),
		new RunePouchLoadoutIcon(SpriteID.MagicNecroOn.FENKENSTRAINS_CASTLE_TELEPORT, "Fenkenstrain's Castle Teleport"),
		new RunePouchLoadoutIcon(SpriteID.MagicNecroOn.WEST_ARDOUGNE_TELEPORT, "West Ardougne Teleport"),
		new RunePouchLoadoutIcon(SpriteID.MagicNecroOn.HARMONY_ISLAND_TELEPORT, "Harmony Island Teleport"),
		new RunePouchLoadoutIcon(SpriteID.MagicNecroOn.BARROWS_TELEPORT, "Barrows Teleport"),
		new RunePouchLoadoutIcon(SpriteID.MagicNecroOn.APE_ATOLL_TELEPORT, "Ape Atoll Teleport"),
		new RunePouchLoadoutIcon(SpriteID.MagicNecroOn.CEMETERY_TELEPORT, "Cemetery Teleport"),
		new RunePouchLoadoutIcon(SpriteID.MagicNecroOn.GHOSTLY_GRASP, "Ghostly Grasp"),
		new RunePouchLoadoutIcon(SpriteID.MagicNecroOn.SKELETAL_GRASP, "Skeletal Grasp"),
		new RunePouchLoadoutIcon(SpriteID.MagicNecroOn.UNDEAD_GRASP, "Undead Grasp"),
		new RunePouchLoadoutIcon(SpriteID.MagicNecroOn.INFERIOR_DEMONBANE, "Inferior Demonbane"),
		new RunePouchLoadoutIcon(SpriteID.MagicNecroOn.SUPERIOR_DEMONBANE, "Superior Demonbane"),
		new RunePouchLoadoutIcon(SpriteID.MagicNecroOn.DARK_DEMONBANE, "Dark Demonbane"),
		new RunePouchLoadoutIcon(SpriteID.MagicNecroOn.MARK_OF_DARKNESS, "Mark of Darkness"),
		new RunePouchLoadoutIcon(SpriteID.MagicNecroOn.WARD_OF_ARCEUUS, "Ward of Arceuus"),
		new RunePouchLoadoutIcon(SpriteID.MagicNecroOn.LESSER_CORRUPTION, "Lesser Corruption"),
		new RunePouchLoadoutIcon(SpriteID.MagicNecroOn.GREATER_CORRUPTION, "Greater Corruption"),
		new RunePouchLoadoutIcon(SpriteID.MagicNecroOn.DEATH_CHARGE, "Death Charge"),
		new RunePouchLoadoutIcon(SpriteID.MagicNecroOn.DEMONIC_OFFERING, "Demonic Offering"),
		new RunePouchLoadoutIcon(SpriteID.MagicNecroOn.SINISTER_OFFERING, "Sinister Offering"),
		new RunePouchLoadoutIcon(SpriteID.MagicNecroOn.SHADOW_VEIL, "Shadow Veil"),
		new RunePouchLoadoutIcon(SpriteID.MagicNecroOn.DARK_LURE, "Dark Lure"),
		new RunePouchLoadoutIcon(SpriteID.MagicNecroOn.VILE_VIGOUR, "Vile Vigour"),
		new RunePouchLoadoutIcon(SpriteID.MagicNecroOn.DEGRIME, "Degrime"),

		new RunePouchLoadoutIcon(SpriteID.SideIcons.MAGIC, "Spellbook Standard"),
		new RunePouchLoadoutIcon(SpriteID.SideIcons.SPELLBOOK_ANCIENT_MAGICKS, "Spellbook Ancient"),
		new RunePouchLoadoutIcon(SpriteID.SideIcons.SPELLBOOK_LUNAR, "Spellbook Lunar"),
		new RunePouchLoadoutIcon(SpriteID.SideIcons.SPELLBOOK_ARCEUUS, "Spellbook Arceuus"),

		new RunePouchLoadoutIcon(SpriteID.Prayeron.PROTECT_FROM_MAGIC, "Protect From Magic"),
		new RunePouchLoadoutIcon(SpriteID.Prayeron.PROTECT_FROM_MISSILES, "Protect From Missiles"),
		new RunePouchLoadoutIcon(SpriteID.Prayeron.PROTECT_FROM_MELEE, "Protect From Melee"),
		new RunePouchLoadoutIcon(SpriteID.Prayeron.REDEMPTION, "Redemption"),
		new RunePouchLoadoutIcon(SpriteID.Prayeron.RETRIBUTION, "Retribution"),
		new RunePouchLoadoutIcon(SpriteID.Prayeron.SMITE, "Smite"),
		new RunePouchLoadoutIcon(SpriteID.Prayeron.CHIVALRY, "Chivalry"),
		new RunePouchLoadoutIcon(SpriteID.Prayeron.PIETY, "Piety"),
		new RunePouchLoadoutIcon(SpriteID.Prayeron.PRESERVE, "Preserve"),
		new RunePouchLoadoutIcon(SpriteID.Prayeron.RIGOUR, "Rigour"),
		new RunePouchLoadoutIcon(SpriteID.Prayeron.AUGURY, "Augury"),
		new RunePouchLoadoutIcon(SpriteID.Prayeron.DEADEYE, "Deadeye"),
		new RunePouchLoadoutIcon(SpriteID.Prayeron.MYSTIC_VIGOUR, "Mystic Vigour"),

		new RunePouchLoadoutIcon(SpriteID.IconPrayerZaros01_30x30.ANCIENT_STRENGTH, "Ancient Strength"),
		new RunePouchLoadoutIcon(SpriteID.IconPrayerZaros01_30x30.ANCIENT_SIGHT, "Ancient Sight"),
		new RunePouchLoadoutIcon(SpriteID.IconPrayerZaros01_30x30.ANCIENT_WILL, "Ancient Will"),
		new RunePouchLoadoutIcon(SpriteID.IconPrayerZaros01_30x30.TRINITAS, "Trinitas"),
		new RunePouchLoadoutIcon(SpriteID.IconPrayerZaros01_30x30.DECIMATE, "Decimate"),
		new RunePouchLoadoutIcon(SpriteID.IconPrayerZaros01_30x30.ANNIHILATE, "Annihilate"),
		new RunePouchLoadoutIcon(SpriteID.IconPrayerZaros01_30x30.VAPORISE, "Vaporise"),
		new RunePouchLoadoutIcon(SpriteID.IconPrayerZaros01_30x30.WRATH, "Wrath"),
		new RunePouchLoadoutIcon(SpriteID.IconPrayerZaros01_30x30.RUINOUS_GRACE, "Ruinous Grace"),
		new RunePouchLoadoutIcon(SpriteID.IconPrayerZaros01_30x30.REJUVENATION, "Rejuvenation"),

		new RunePouchLoadoutIcon(SpriteID.IconBoss25x25.ABYSSAL_SIRE, "Abyssal Sire"),
		new RunePouchLoadoutIcon(SpriteID.IconBoss25x25.ALCHEMICAL_HYDRA, "Alchemical Hydra"),
		new RunePouchLoadoutIcon(SpriteID.IconBoss25x25.AMOXLIATL, "Amoxliatl"),
		new RunePouchLoadoutIcon(SpriteID.IconBoss25x25.THE_HUEYCOATL, "The Hueycoatl"),
		new RunePouchLoadoutIcon(SpriteID.IconBoss25x25.ROYAL_TITANS, "Royal Titans"),
		new RunePouchLoadoutIcon(SpriteID.IconBoss25x25.YAMA, "Yama"),
		new RunePouchLoadoutIcon(SpriteID.IconBoss25x25.DOOM_OF_MOKHAIOTL, "Doom of Mokhaiotl"),
		new RunePouchLoadoutIcon(SpriteID.IconBoss25x25.MIMIC, "Mimic"),
		new RunePouchLoadoutIcon(SpriteID.IconBoss25x25.OBOR, "Obor"),
		new RunePouchLoadoutIcon(SpriteID.IconBoss25x25.ARAXXOR, "Araxxor"),
		new RunePouchLoadoutIcon(SpriteID.IconBoss25x25.BRYOPHYTA, "Bryophyta"),
		new RunePouchLoadoutIcon(SpriteID.IconBoss25x25.GIANT_MOLE, "Giant Mole"),
		new RunePouchLoadoutIcon(SpriteID.IconBoss25x25.GROTESQUE_GUARDIANS, "Grotesque Guardians"),
		new RunePouchLoadoutIcon(SpriteID.IconBoss25x25.TEMPOROSS, "Tempoross"),
		new RunePouchLoadoutIcon(SpriteID.IconBoss25x25.WINTERTODT, "Wintertodt"),
		new RunePouchLoadoutIcon(SpriteID.IconBoss25x25.BARROWS_CHESTS, "Barrows Chests"),
		new RunePouchLoadoutIcon(SpriteID.IconBoss25x25.SARACHNIS, "Sarachnis"),
		new RunePouchLoadoutIcon(SpriteID.IconBoss25x25.KALPHITE_QUEEN, "Kalphite Queen"),
		new RunePouchLoadoutIcon(SpriteID.IconBoss25x25.HESPORI, "Hespori"),
		new RunePouchLoadoutIcon(SpriteID.IconBoss25x25.SKOTIZO, "Skotizo"),
		new RunePouchLoadoutIcon(SpriteID.IconBoss25x25.ZALCANO, "Zalcano"),
		new RunePouchLoadoutIcon(SpriteID.IconBoss25x25.KING_BLACK_DRAGON, "King Black Dragon"),
		new RunePouchLoadoutIcon(SpriteID.IconBoss25x25.KRAKEN, "Kraken"),
		new RunePouchLoadoutIcon(SpriteID.IconBoss25x25.THERMONUCLEAR_SMOKE_DEVIL, "Thermonuclear Smoke Devil"),
		new RunePouchLoadoutIcon(SpriteID.IconBoss25x25.THE_GAUNTLET, "The Gauntlet"),
		new RunePouchLoadoutIcon(SpriteID.IconBoss25x25.THE_CORRUPTED_GAUNTLET, "The Corrupted Gauntlet"),
		new RunePouchLoadoutIcon(SpriteID.IconBoss25x25.ZULRAH, "Zulrah"),
		new RunePouchLoadoutIcon(SpriteID.IconBoss25x25.CERBERUS, "Cerberus"),
		new RunePouchLoadoutIcon(SpriteID.IconBoss25x25.VORKATH, "Vorkath"),
		new RunePouchLoadoutIcon(SpriteID.IconBoss25x25.GENERAL_GRAARDOR, "General Graardor"),
		new RunePouchLoadoutIcon(SpriteID.IconBoss25x25.KRIL_TSUTSAROTH, "Kril Tsutsaroth"),
		new RunePouchLoadoutIcon(SpriteID.IconBoss25x25.COMMANDER_ZILYANA, "Commander Zilyana"),
		new RunePouchLoadoutIcon(SpriteID.IconBoss25x25.KREEARRA, "Kree'arra"),
		new RunePouchLoadoutIcon(SpriteID.IconBoss25x25.NIGHTMARE, "Nightmare"),
		new RunePouchLoadoutIcon(SpriteID.IconBoss25x25.CORPOREAL_BEAST, "Corporeal Beast"),
		new RunePouchLoadoutIcon(SpriteID.IconBoss25x25.CHAMBERS_OF_XERIC, "Chambers of Xeric"),
		new RunePouchLoadoutIcon(SpriteID.IconBoss25x25.CHAMBERS_OF_XERIC_CHALLENGE_MODE, "Chambers of Xeric Challenge Mode"),
		new RunePouchLoadoutIcon(SpriteID.IconBoss25x25.THEATRE_OF_BLOOD, "Theatre of Blood"),
		new RunePouchLoadoutIcon(SpriteID.IconBoss25x25.TOMBS_OF_AMASCUT, "Tombs of Amascut"),
		new RunePouchLoadoutIcon(SpriteID.IconBoss25x25.TOMBS_OF_AMASCUT_EXPERT, "Tombs of Amascut Expert"),
		new RunePouchLoadoutIcon(SpriteID.IconBoss25x25.NEX, "Nex"),
		new RunePouchLoadoutIcon(SpriteID.IconBoss25x25.DAGANNOTH_SUPREME, "Dagannoth Supreme"),
		new RunePouchLoadoutIcon(SpriteID.IconBoss25x25.DAGANNOTH_REX, "Dagannoth Rex"),
		new RunePouchLoadoutIcon(SpriteID.IconBoss25x25.DAGANNOTH_PRIME, "Dagannoth Prime"),
		new RunePouchLoadoutIcon(SpriteID.IconBoss25x25.PHANTOM_MUSPAH, "Phantom Muspah"),
		new RunePouchLoadoutIcon(SpriteID.IconBoss25x25.CHAOS_ELEMENTAL, "Chaos Elemental"),
		new RunePouchLoadoutIcon(SpriteID.IconBoss25x25.ARTIO_CALLISTO, "Artio Callisto"),
		new RunePouchLoadoutIcon(SpriteID.IconBoss25x25.CALVARION_VETION, "Calvarion Vetion"),
		new RunePouchLoadoutIcon(SpriteID.IconBoss25x25.SPINDEL_VENENATIS, "Spindel Venenatis"),
		new RunePouchLoadoutIcon(SpriteID.IconBoss25x25.CHAOS_FANATIC, "Chaos Fanatic"),
		new RunePouchLoadoutIcon(SpriteID.IconBoss25x25.CRAZY_ARCHAEOLOGIST, "Crazy Archaeologist"),
		new RunePouchLoadoutIcon(SpriteID.IconBoss25x25.DERANGED_ARCHAEOLOGIST, "Deranged Archaeologist"),
		new RunePouchLoadoutIcon(SpriteID.IconBoss25x25.SCORPIA, "Scorpia"),
		new RunePouchLoadoutIcon(SpriteID.IconBoss25x25.TZTOK_JAD, "TzTok Jad"),
		new RunePouchLoadoutIcon(SpriteID.IconBoss25x25.TZKAL_ZUK, "TzKal Zuk"),
		new RunePouchLoadoutIcon(SpriteID.IconBoss25x25.THE_WHISPERER, "The Whisperer"),
		new RunePouchLoadoutIcon(SpriteID.IconBoss25x25.DUKE_SUCELLUS, "Duke Sucellus"),
		new RunePouchLoadoutIcon(SpriteID.IconBoss25x25.THE_LEVIATHAN, "The Leviathan"),
		new RunePouchLoadoutIcon(SpriteID.IconBoss25x25.VARDORVIS, "Vardorvis"),
		new RunePouchLoadoutIcon(SpriteID.IconBoss25x25.SCURRIUS, "Scurrius"),
		new RunePouchLoadoutIcon(SpriteID.IconBoss25x25.SOL_HEREDIT, "Sol Heredit"),
		new RunePouchLoadoutIcon(SpriteID.IconBoss25x25.LUNAR_CHESTS, "Lunar Chests"),
		new RunePouchLoadoutIcon(SpriteID.IconBoss25x25.MAGGOT_KING, "Maggot King"),

		new RunePouchLoadoutIcon(SpriteID.Staticons.ATTACK, "Attack"),
		new RunePouchLoadoutIcon(SpriteID.Staticons.STRENGTH, "Strength"),
		new RunePouchLoadoutIcon(SpriteID.Staticons.DEFENCE, "Defence"),
		new RunePouchLoadoutIcon(SpriteID.Staticons.RANGED, "Ranged"),
		new RunePouchLoadoutIcon(SpriteID.Staticons.PRAYER, "Prayer"),
		new RunePouchLoadoutIcon(SpriteID.Staticons.MAGIC, "Magic"),
		new RunePouchLoadoutIcon(SpriteID.Staticons.HITPOINTS, "Hitpoints"),
		new RunePouchLoadoutIcon(SpriteID.Staticons.AGILITY, "Agility"),
		new RunePouchLoadoutIcon(SpriteID.Staticons.HERBLORE, "Herblore"),
		new RunePouchLoadoutIcon(SpriteID.Staticons.THIEVING, "Thieving"),
		new RunePouchLoadoutIcon(SpriteID.Staticons.CRAFTING, "Crafting"),
		new RunePouchLoadoutIcon(SpriteID.Staticons.FLETCHING, "Fletching"),
		new RunePouchLoadoutIcon(SpriteID.Staticons.MINING, "Mining"),
		new RunePouchLoadoutIcon(SpriteID.Staticons.SMITHING, "Smithing"),
		new RunePouchLoadoutIcon(SpriteID.Staticons.FISHING, "Fishing"),
		new RunePouchLoadoutIcon(SpriteID.Staticons.COOKING, "Cooking"),
		new RunePouchLoadoutIcon(SpriteID.Staticons.FIREMAKING, "Firemaking"),
		new RunePouchLoadoutIcon(SpriteID.Staticons.WOODCUTTING, "Woodcutting")
	);
}
